### ISSUE TITLE
Enchanted items z-fight in item frames

### ISSUE THREAD

**Issue by Jiingy** [ewanhowell5195/F8thful#1]
Issue:
https://github.com/ewanhowell5195/F8thful/assets/69827559/0d5226eb-bbbb-49f9-a20b-f9eacdc5e7c0

Fix:
Modify the base item model to be 0.25 away from item frames
put this in `assets/minecraft/models/item`:
[generated.json](https://github.com/ewanhowell5195/F8thful/files/13855231/generated.json)

![image](https://github.com/ewanhowell5195/F8thful/assets/69827559/d6cb9d6d-ead4-4db8-b17d-f77e28372958)

**Comment by ewanhowell5195** [comment]
![what](https://github.com/ewanhowell5195/F8thful/assets/48070995/866261c4-d326-4a97-a1f1-ff8a4b213251)
